version: '3.7'
services:
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/config/custom.ini:/etc/grafana/grafana.ini
      
volumes:
  grafana-data: